<!DOCTYPE html>
<html lang="en">
<?php include TEMPLATE_PATH . "Head.tmpl.phtml"; ?>
<body class="dark-mode with-custom-webkit-scrollbars with-custom-css-scrollbars" data-dm-shortcut-enabled="true" data-sidebar-shortcut-enabled="true">

<!-- Page wrapper start -->
<div id="page-wrapper" class="page-wrapper with-navbar with-sidebar" data-sidebar-type="default">

    <!-- Sticky alerts -->
    <div class="sticky-alerts"></div>

    <?php include ADMIN_TEMPLATE_PATH . "Nav.tmpl.phtml"; ?>

    <?php include ADMIN_TEMPLATE_PATH . "Sidebar.tmpl.phtml"; ?>

    <!-- Sidebar overlay -->
    <div class="sidebar-overlay" onclick="halfmoon.toggleSidebar()"></div>

    <!-- Content wrapper start -->
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row row-eq-spacing-lg">
                <div class="col-lg-3"></div>
                <div class="col-lg-6">
                    <h3 class="text-center">Add new musician</h3>
                    <div class="content">
                        <form action="<?= URL_ROOT . "musician/editSubmit/" . $data['musician']->getId(); ?>" method="POST" enctype="multipart/form-data">

                            <!-- Name -->
                            <div class="form-group <?= isset($_SESSION['form_errors']['name']) ? 'is-invalid' : ''; ?>">
                                <label for="name" class="required font-weight-bold">Name</label>
                                <input type="text" class="form-control"
                                       value="<?= $data['musician']->getName(); ?>"
                                       name="name" id="name" placeholder="Name" required="required">
                                <small class="text-danger"><?= isset($_SESSION['form_errors']['name']) ? $_SESSION['form_errors']['name'] : ''; ?></small>
                            </div>

                            <!-- Description -->
                            <div class="form-group <?= isset($_SESSION['form_errors']['description']) ? 'is-invalid' : ''; ?>">
                                    <textarea class="form-control alt-dm" name="description" style="min-height: 30rem;">
                                        <?= $data['musician']->getDescription(); ?>
                                    </textarea>
                                <small class="text-danger"><?= isset($_SESSION['form_errors']['description']) ? $_SESSION['form_errors']['description'] : ''; ?></small>
                                </div>
                            </div>

                            <!-- Image -->
                            <div class="custom-file pb-20">
                                <input type="file" id="file-input" name="image" data-default-value="No image chosen"
                                       class="<?= isset($_SESSION['form_errors']['image']) ? 'is-invalid' : ''; ?>">
                                <label for="file-input">Choose an image</label>
                                <small class="text-danger"><?= isset($_SESSION['form_errors']['image']) ? $_SESSION['form_errors']['image'] : ''; ?></small>
                            </div>

                            <input class="btn btn-primary btn-block" type="submit" value="Add">
                        </form>
                    </div>
                </div>
                <div class="col-lg-3"></div>

            </div>
        </div>
    </div>
    <!-- Content wrapper end -->

</div>
<!-- Page wrapper end -->
<?php include TEMPLATE_PATH . "Scripts.tmpl.phtml"; ?>

</body>
</html>
