<!-- Navbar start -->
<nav class="navbar">
    <div class="navbar-content">
        <div class="navbar-content">


        </div>
        <!-- Navbar brand -->
        <a href="<?= URL_ROOT; ?>" class="navbar-brand">
            <img src="/assets/eventzone_logo_gradient.png" alt="logo">
        </a>

        <a href="<?= URL_ROOT; ?>events">
            <button class="btn mr-10 text-dark font-weight-bold" type="button"
                    style="background: linear-gradient(to left, #ff8c2e, #ff4500);">
                    Events
            </button>
        </a>

        <a href="<?= URL_ROOT; ?>musicians">
            <button class="btn text-dark font-weight-bold" type="button"
                    style="background: linear-gradient(to right, #ff8c2e, #ff4500);">
                    Musicians
            </button>
        </a>
    </div>

    <div class="navbar-content ml-auto">
        <a href="<?= URL_ROOT; ?>#register">
            <button class="btn btn-primary shadow" type="button">Sign up</button>
        </a>

    </div>

</nav>
<!-- Navbar end -->