<!-- Navbar start -->
<nav class="navbar">
    <div class="navbar-content">
        <div class="navbar-content">


        </div>
        <!-- Navbar brand -->
        <a href="<?= URL_ROOT; ?>" class="navbar-brand">
            <img src="/assets/eventzone_logo_gradient.png" alt="logo">
        </a>

        <a href="<?= URL_ROOT; ?>events">
            <button class="btn mr-10 text-dark font-weight-bold" type="button"
                    style="background: linear-gradient(to left, #ff8c2e, #ff4500); border: none;">
                    Events
            </button>
        </a>

        <a href="<?= URL_ROOT; ?>musicians">
            <button class="btn text-dark font-weight-bold" type="button"
                    style="background: linear-gradient(to right, #ff8c2e, #ff4500); border: none;">
                    Musicians
            </button>
        </a>
    </div>

    <div class="navbar-content ml-auto">
        <?php if (!\Core\Auth::getInstance()->isLoggedIn()): ?>
        <a href="<?= URL_ROOT; ?>#register">
            <button class="btn btn-primary shadow" type="button">Sign up</button>
        </a>
        <?php else: ?>
        <div class="dropdown toggle-on-hover">
            <button class="btn" data-toggle="dropdown" type="button" id="" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user ml-5" aria-hidden="true"></i> Account <i class="fa fa-angle-down ml-5" aria-hidden="true"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="...">
                <a href="#" class="dropdown-item">Link 1</a>
                <a href="#" class="dropdown-item">Link 2</a>
                <div class="dropdown-divider"></div>
                <div class="dropdown-content">
                    <a href="login/logoutSubmit">
                    <button class="btn btn-block btn-danger" type="button">Sign out</button>
                    </a>
                </div>
            </div>
        </div>
        <?php endif ?>
    </div>



</nav>
<!-- Navbar end -->