<!-- Navbar start -->
<nav class="navbar">
    <div class="navbar-content">
        <button id="toggle-sidebar-btn" class="btn btn-action" type="button" onclick="halfmoon.toggleSidebar()">
            <i class="fa fa-bars" aria-hidden="true"></i>
        </button>
    </div>
    <a href="#" class="navbar-brand ml-10 ml-sm-20">
        <img src="/assets/eventzone_logo_gradient.png" alt="fake-logo">
    </a>
    <div class="navbar-content ml-auto">
        <button class="btn btn-action mr-5" type="button" onclick="halfmoon.toggleDarkMode()">
            <i class="fas fa-moon" aria-hidden="true"></i>
            <span class="sr-only">Toggle dark mode</span>
        </button>

        <a href="<?= URL_ROOT . 'login/logoutSubmit'?>">
            <button class="btn btn-action mr-5" type="button">
                <i class="fas fa-sign-out-alt" aria-hidden="true"></i>
                <span class="sr-only">Log out</span>
            </button>
        </a>

    </div>
</nav>
<!-- Navbar end -->