<!-- Sidebar start -->
<div class="sidebar">
    <div class="sidebar-menu">

        <h5 class="sidebar-title"><i class="fa fa-user-shield" aria-hidden="true"></i> Administrators</h5>
        <div class="sidebar-divider"></div>

        <a href="<?= URL_ROOT . 'admin/list'; ?>" class="sidebar-link sidebar-link-with-icon">
            <span class="sidebar-icon">
                 <i class="fa fa-list" aria-hidden="true"></i>
            </span>
            List
        </a>

        <a href="<?= URL_ROOT . 'admin/create'; ?>" class="sidebar-link sidebar-link-with-icon">
            <span class="sidebar-icon">
                 <i class="fa fa-plus" aria-hidden="true"></i>
            </span>
            Add
        </a>

        <br />

        <h5 class="sidebar-title"><i class="fa fa-calendar" aria-hidden="true"></i> Events</h5>
        <div class="sidebar-divider"></div>

        <a href="#" class="sidebar-link sidebar-link-with-icon">
            <span class="sidebar-icon">
                <i class="fa fa-list" aria-hidden="true"></i>
            </span>
            List
        </a>

        <a href="#" class="sidebar-link sidebar-link-with-icon">
            <span class="sidebar-icon">
                <i class="fa fa-plus" aria-hidden="true"></i>
            </span>
            Add
        </a>

        <br />

        <h5 class="sidebar-title"><i class="fa fa-music" aria-hidden="true"></i> Musicians</h5>
        <div class="sidebar-divider"></div>

        <a href="#" class="sidebar-link sidebar-link-with-icon">
            <span class="sidebar-icon">
                <i class="fa fa-list" aria-hidden="true"></i>
            </span>
            List
        </a>

        <a href="#" class="sidebar-link sidebar-link-with-icon">
            <span class="sidebar-icon">
                <i class="fa fa-plus" aria-hidden="true"></i>
            </span>
            Add
        </a>

        <br />

        <h5 class="sidebar-title"><i class="fa fa-users" aria-hidden="true"></i> Users</h5>
        <div class="sidebar-divider"></div>

        <a href="#" class="sidebar-link sidebar-link-with-icon">
            <span class="sidebar-icon">
                 <i class="fa fa-list" aria-hidden="true"></i>
            </span>
            List
        </a>

        <br />

        <h5 class="sidebar-title"><i class="fas fa-ticket-alt" aria-hidden="true"></i> Orders</h5>
        <div class="sidebar-divider"></div>

        <a href="#" class="sidebar-link sidebar-link-with-icon">
            <span class="sidebar-icon">
                <i class="fa fa-list" aria-hidden="true"></i>
            </span>
            List
        </a>

    </div>
</div>
<!-- Sidebar end -->