<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta tags -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <meta name="viewport" content="width=device-width" />

    <!-- Chrome, Firefox OS and Opera mobile address bar theming -->
    <meta name="theme-color" content="#000000">
    <!-- Windows Phone mobile address bar theming -->
    <meta name="msapplication-navbutton-color" content="#000000">
    <!-- iOS Safari mobile address bar theming -->
    <meta name="apple-mobile-web-app-status-bar-style" content="#000000">

    <!-- SEO -->
    <meta name="description" content="Purchase concert, music, and festival tickets at the official EventZone shop.">
    <meta name="author" content="EventZone">
    <meta name="keywords" content="ticket, concert ticket, music ticket, festival ticket, music, festival, concert, artist, musician">

    <!-- Open graph -->
    <meta property="og:type" content="article">
    <meta property="og:url" content=""> <!-- INSERT FINAL URL HERE -->
    <meta property="og:title" content="Croatia's leading event booking retailer for events, concerts and festivals.">
    <meta property="og:description" content="Book events at the official EventZone shop.">
    <meta property="og:image" content=""> <!-- INSERT FINAL LOGO HERE -->
    <meta name="twitter:card" content="summary_large_image">

    <!-- Favicon and title -->
    <link rel="icon" href="path/to/fav.png">
    <title><?= isset($title) ? SITE_NAME . ' | ' . $title : SITE_NAME ?></title>

    <!-- Halfmoon CSS -->
    <link href="css/halfmoon.css" rel="stylesheet" />

    <!-- Font Awesome 5.14.0 -->
    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js" integrity="sha384-3Nqiqht3ZZEO8FKj7GR1upiI385J92VwWNLj+FqHxtLYxd9l+WYpeqSOrLh0T12c" crossorigin="anonymous"></script>

    <!-- Project CSS -->
    <link href="css/style.css" rel="stylesheet" >

</head>
<body class="dark-mode with-custom-webkit-scrollbars with-custom-css-scrollbars" data-dm-shortcut-enabled="true" data-sidebar-shortcut-enabled="true">

<!-- Page wrapper start -->
<div id="page-wrapper" class="page-wrapper with-navbar with-sidebar" data-sidebar-type="default">

    <!-- Sticky alerts -->
    <div class="sticky-alerts"></div>

    <!-- Navbar start -->
    <nav class="navbar">
        <div class="navbar-content">
            <div class="navbar-content">

            </div>
            <!-- Navbar brand -->
            <a href="<?= URL_ROOT; ?>" class="navbar-brand">
                <img src="../assets/eventzone_logo_gradient.png" alt="logo">
            </a>

            <?php if (\Core\Auth::getInstance()->isLoggedIn()): ?>
                <a href="<?= URL_ROOT; ?>event/view">
                    <button class="btn btn-sm mr-10 text-dark font-weight-bold" type="button"
                            style="background: linear-gradient(to left, #ff8c2e, #ff4500); border: none;">
                        <i class="fa fa-calendar-alt" aria-hidden="true"></i>
                        Events
                    </button>
                </a>
            <?php endif ?>

            <a href="<?= URL_ROOT; ?>musician/view">
                <button class="btn btn-sm mr-10 text-dark font-weight-bold" type="button"
                        style="background: linear-gradient(to right, #ff8c2e, #ff4500); border: none;">
                    <i class="fa fa-music" aria-hidden="true"></i>
                    Musicians
                </button>
            </a>

            <a href="<?= URL_ROOT; ?>venue/view">
                <button class="btn btn-sm text-dark font-weight-bold" type="button"
                        style="background: linear-gradient(to right, #ff4500, #ff8c2e); border: none;">
                    <i class="fas fa-map-marked-alt" aria-hidden="true"></i>
                    Venues
                </button>
            </a>
        </div>

        <div class="navbar-content ml-auto">
            <?php if (!\Core\Auth::getInstance()->isLoggedIn()): ?>
                <a href="<?= URL_ROOT; ?>#register">
                    <button class="btn btn-primary shadow" type="button">Sign up</button>
                </a>
            <?php else: ?>
                <div class="dropdown toggle-on-hover">
                    <button class="btn" data-toggle="dropdown" type="button" id="" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user ml-5" aria-hidden="true"></i> Account <i class="fa fa-angle-down ml-5" aria-hidden="true"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="...">
                        <?php if (\Core\Auth::getInstance()->getCurrentUser()->getIsAdmin()): ?>
                            <a href="<?= URL_ROOT; ?>management" class="dropdown-item">Management</a>
                        <?php else: ?>
                            <a href="<?= URL_ROOT; ?>user/settings" class="dropdown-item">Settings</a>
                        <?php endif ?>
                        <div class="dropdown-divider"></div>
                        <div class="dropdown-content">
                            <a href="<?= URL_ROOT; ?>login/logoutSubmit">
                                <button class="btn btn-block btn-danger" type="button">Sign out</button>
                            </a>
                        </div>
                    </div>
                </div>
            <?php endif ?>
        </div>
    </nav>
    <!-- Navbar end -->

    <?php include ADMIN_TEMPLATE_PATH . "Sidebar.tmpl.phtml"; ?>

    <!-- Sidebar overlay -->
    <div class="sidebar-overlay" onclick="halfmoon.toggleSidebar()"></div>

    <!-- Content wrapper start -->
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row row-eq-spacing-lg">
                <div class="col-lg-3"></div>
                <div class="col-lg-6">
                    <h3 class="text-center">Add new venue</h3>
                    <div class="content">
                        <form action="<?= URL_ROOT . "venue/createSubmit"?>" method="POST" enctype="multipart/form-data">

                            <div class="form-row row-eq-spacing-sm">

                                <!-- Name -->
                                <div class="col-sm form-group <?= isset($_SESSION['form_errors']['name']) ? 'is-invalid' : ''; ?>">
                                    <label for="name" class="required font-weight-bold">Name</label>
                                    <input type="text" class="form-control"
                                           value="<?= isset($_SESSION['form_data']['name']) ? $_SESSION['form_data']['name'] : ''; ?>"
                                           name="name" id="name" placeholder="Name" required="required">
                                    <small class="text-danger"><?= isset($_SESSION['form_errors']['name']) ? $_SESSION['form_errors']['name'] : ''; ?></small>
                                </div>

                                <!-- Capacity -->
                                <div class="col-sm form-group <?= isset($_SESSION['form_errors']['capacity']) ? 'is-invalid' : ''; ?>">
                                    <label for="capacity" class="required font-weight-bold">Capacity</label>
                                    <input type="text" class="form-control"
                                           value="<?= isset($_SESSION['form_data']['capacity']) ? $_SESSION['form_data']['capacity'] : ''; ?>"
                                           name="capacity" id="capacity" placeholder="Capacity" required="required">
                                    <small class="text-danger"><?= isset($_SESSION['form_errors']['capacity']) ? $_SESSION['form_errors']['capacity'] : ''; ?></small>
                                </div>

                            </div>

                            <!-- Image -->
                            <label class="font-weight-bold required">Image</label>
                            <div class="custom-file pb-20">
                                <input type="file" id="file-input" name="image" data-default-value="No image chosen"
                                class="<?= isset($_SESSION['form_errors']['image']) ? 'is-invalid' : ''; ?>">
                                <label for="file-input" style="width: 100%; text-align: center;">Choose an image</label>
                                <small class="text-danger"><?= isset($_SESSION['form_errors']['image']) ? $_SESSION['form_errors']['image'] : ''; ?></small>
                            </div>

                            <div class="form-row row-eq-spacing-sm">

                                <!-- Address -->
                                <div class="col-sm form-group <?= isset($_SESSION['form_errors']['address']) ? 'is-invalid' : ''; ?>">
                                    <label for="last-name" class="required font-weight-bold">Address</label>
                                    <input type="text" class="form-control"
                                           value="<?= isset($_SESSION['form_data']['address']) ? $_SESSION['form_data']['address'] : ''; ?>"
                                           name="address" id="last-name" placeholder="Address" required="required">
                                    <small class="text-danger"><?= isset($_SESSION['form_errors']['address']) ? $_SESSION['form_errors']['address'] : ''; ?></small>
                                </div>

                                <!-- City -->
                                <div class="col-sm form-group <?= isset($_SESSION['form_errors']['city']) ? 'is-invalid' : ''; ?>">
                                    <label for="city" class="required font-weight-bold">City</label>
                                    <input type="text" class="form-control"
                                           value="<?= isset($_SESSION['form_data']['city']) ? $_SESSION['form_data']['city'] : ''; ?>"
                                           name="city" id="city" placeholder="City" required="required">
                                    <small class="text-danger"><?= isset($_SESSION['form_errors']['city']) ? $_SESSION['form_errors']['city'] : ''; ?></small>
                                </div>

                            </div>

                            <div class="form-row row-eq-spacing-sm">

                                <!-- Postal Code -->
                                <div class="col-sm form-group <?= isset($_SESSION['form_errors']['postcode']) ? 'is-invalid' : ''; ?>">
                                    <label for="last-name" class="required font-weight-bold">Postal Code</label>
                                    <input type="text" class="form-control"
                                           value="<?= isset($_SESSION['form_data']['postcode']) ? $_SESSION['form_data']['postcode'] : ''; ?>"
                                           name="postcode" id="last-name" placeholder="Last name" required="required">
                                    <small class="text-danger"><?= isset($_SESSION['form_errors']['postcode']) ? $_SESSION['form_errors']['postcode'] : ''; ?></small>
                                </div>

                                <!-- Country -->
                                <div class="col-sm form-group <?= isset($_SESSION['form_errors']['country']) ? 'is-invalid' : ''; ?>">
                                    <label for="country" class="required font-weight-bold">Country</label>
                                    <input type="text" class="form-control"
                                           value="<?= isset($_SESSION['form_data']['country']) ? $_SESSION['form_data']['country'] : ''; ?>"
                                           name="country" id="country" placeholder="Country" required="required">
                                    <small class="text-danger"><?= isset($_SESSION['form_errors']['country']) ? $_SESSION['form_errors']['country'] : ''; ?></small>
                                </div>

                            </div>

                            <input class="btn btn-primary btn-block" type="submit" value="Add">
                        </form>
                    </div>
                </div>
                <div class="col-lg-3"></div>

            </div>
        </div>
    </div>
    <!-- Content wrapper end -->

</div>
<!-- Page wrapper end -->
<?php include TEMPLATE_PATH . "Scripts.tmpl.phtml"; ?>

</body>
</html>
