<!DOCTYPE html>
<html lang="en">
<?php include TEMPLATE_PATH . "Head.tmpl.phtml"; ?>
<body class="dark-mode with-custom-webkit-scrollbars with-custom-css-scrollbars" data-dm-shortcut-enabled="true" data-sidebar-shortcut-enabled="true">

<!-- Page wrapper start -->
<div id="page-wrapper" class="page-wrapper with-navbar with-sidebar" data-sidebar-type="default">

    <!-- Sticky alerts -->
    <div class="sticky-alerts"></div>

    <?php include ADMIN_TEMPLATE_PATH . "Nav.tmpl.phtml"; ?>

    <?php include ADMIN_TEMPLATE_PATH . "Sidebar.tmpl.phtml"; ?>

    <!-- Sidebar overlay -->
    <div class="sidebar-overlay" onclick="halfmoon.toggleSidebar()"></div>

    <!-- Content wrapper start -->
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row row-eq-spacing-lg">
                <div class="col-lg-12">

                    <div class="content">
                        <h3>Venue List</h3>
                        <table class="table table-hover table-responsive">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Capacity</th>
                                <th>Image</th>
                                <th>Address</th>
                                <th>Actions</th>
                            </tr>
                            </thead>

                            <tbody>
                            <?php foreach ($data['venues'] as $venue) :?>
                            <tr>
                                <th><?= $venue->getId(); ?></th>
                                <td><?= $venue->getName(); ?></td>
                                <td><?= $venue->getCapacity(); ?></td>
                                <td><img src="/assets/venues/Test_5f762f450144b.png" alt="<?= $venue->getImage(); ?>"></td>
                                <td><?= $venue->getAddress(); ?></td>
                                <td>
                                    <a href="edit/<?= $venue->getId(); ?>" class="btn btn-square">
                                    <span>
                                         <i class="fa fa-edit" aria-hidden="true"></i>
                                    </span>
                                    </a>

                                    <form action="deleteSubmit/<?= $venue->getId(); ?>" method="post">
                                        <button class="btn btn-square" name="deleteSubmit">
                                    <span>
                                         <i class="fa fa-trash" aria-hidden="true"></i>
                                    </span>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                            </tbody>

                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Content wrapper end -->

</div>
<!-- Page wrapper end -->
<?php include TEMPLATE_PATH . "Scripts.tmpl.phtml"; ?>

</body>
</html>
