<!DOCTYPE html>
<html lang="en">
<?php include TEMPLATE_PATH . "Head.tmpl.phtml"; ?>
<body class="dark-mode with-custom-webkit-scrollbars with-custom-css-scrollbars" data-dm-shortcut-enabled="true">

<!-- Page wrapper start -->
<div id="page-wrapper" class="page-wrapper">

    <div class="centered" id="logo-container">
        <img src="/assets/500.png" class="img-fluid" id="logo" alt="">
    </div>

    <div class="container-fluid">
        <div id="particles-error-js"></div>
    </div>

</div>
<!-- Page wrapper end -->

<?php include TEMPLATE_PATH . "ErrorScripts.tmpl.phtml"; ?>
</body>
</html>