<!DOCTYPE html>
<html lang="en">

<?php include TEMPLATE_PATH . "Head.tmpl.phtml"; ?>

<body class="with-custom-webkit-scrollbars with-custom-css-scrollbars" data-dm-shortcut-enabled="true">
<!-- Modals go here -->
<!-- Reference: https://www.gethalfmoon.com/docs/modal -->

<!-- Page wrapper start -->
<div class="page-wrapper with-navbar with-navbar-fixed-bottom">

    <!-- Sticky alerts (toasts), empty container -->
    <!-- Reference: https://www.gethalfmoon.com/docs/sticky-alerts-toasts -->
    <div class="sticky-alerts"></div>

    <?php include TEMPLATE_PATH . "Nav.tmpl.phtml"; ?>

    <!-- Content wrapper start -->
    <div class="content-wrapper">
        <!--
          Add your page's main content here
          Examples:
          1. https://www.gethalfmoon.com/docs/content-and-cards/#building-a-page
          2. https://www.gethalfmoon.com/docs/grid-system/#building-a-dashboard
        -->
    </div>
    <!-- Content wrapper end -->

    <?php include TEMPLATE_PATH . "Footer.tmpl.phtml"; ?>

</div>
<!-- Page wrapper end -->

<?php include TEMPLATE_PATH . "Scripts.tmpl.phtml"; ?>
</body>
</html>