<!DOCTYPE html>
<html lang="en">
<?php include TEMPLATE_PATH . "Head.tmpl.phtml"; ?>

<body class="dark-mode with-custom-webkit-scrollbars with-custom-css-scrollbars" data-dm-shortcut-enabled="true">

<!-- Page wrapper start -->
<div id="page-wrapper" class="page-wrapper with-navbar with-navbar-fixed-bottom">

    <!-- Register Modal -->
    <?php include VIEW_PATH . "Pages/Register.view.phtml"; ?>

    <!-- Login Modal -->
    <?php include VIEW_PATH . "Pages/Login.view.phtml"; ?>

    <!-- Sticky alerts -->
    <div class="sticky-alerts"></div>

    <!-- Navbar start -->
    <nav class="navbar">
        <div class="navbar-content">
            <div class="navbar-content">

            </div>
            <!-- Navbar brand -->
            <a href="<?= URL_ROOT; ?>" class="navbar-brand">
                <img src="../assets/eventzone_logo_gradient.png" alt="logo">
            </a>

            <?php if (\Core\Auth::getInstance()->isLoggedIn()): ?>
                <a href="<?= URL_ROOT; ?>event/view">
                    <button class="btn btn-sm mr-10 text-dark font-weight-bold" type="button"
                            style="background: linear-gradient(to left, #ff8c2e, #ff4500); border: none;">
                        <i class="fa fa-calendar-alt" aria-hidden="true"></i>
                        Events
                    </button>
                </a>
            <?php endif ?>

            <a href="<?= URL_ROOT; ?>musician/view">
                <button class="btn btn-sm mr-10 text-dark font-weight-bold" type="button"
                        style="background: linear-gradient(to right, #ff8c2e, #ff4500); border: none;">
                    <i class="fa fa-music" aria-hidden="true"></i>
                    Musicians
                </button>
            </a>

            <a href="<?= URL_ROOT; ?>venue/view">
                <button class="btn btn-sm text-dark font-weight-bold" type="button"
                        style="background: linear-gradient(to right, #ff4500, #ff8c2e); border: none;">
                    <i class="fas fa-map-marked-alt" aria-hidden="true"></i>
                    Venues
                </button>
            </a>
        </div>

        <div class="navbar-content ml-auto">
            <?php if (!\Core\Auth::getInstance()->isLoggedIn()): ?>
                <a href="<?= URL_ROOT; ?>#register">
                    <button class="btn btn-primary shadow" type="button">Sign up</button>
                </a>
            <?php else: ?>
                <div class="dropdown toggle-on-hover">
                    <button class="btn" data-toggle="dropdown" type="button" id="" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user ml-5" aria-hidden="true"></i> Account <i class="fa fa-angle-down ml-5" aria-hidden="true"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="...">
                        <?php if (\Core\Auth::getInstance()->getCurrentUser()->getIsAdmin()): ?>
                            <a href="<?= URL_ROOT; ?>management" class="dropdown-item">Management</a>
                        <?php else: ?>
                            <a href="<?= URL_ROOT; ?>user/settings" class="dropdown-item">Settings</a>
                        <?php endif ?>
                        <div class="dropdown-divider"></div>
                        <div class="dropdown-content">
                            <a href="<?= URL_ROOT; ?>login/logoutSubmit">
                                <button class="btn btn-block btn-danger" type="button">Sign out</button>
                            </a>
                        </div>
                    </div>
                </div>
            <?php endif ?>
        </div>
    </nav>
    <!-- Navbar end -->

    <!-- Content wrapper start -->
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="card border">
            <div class="row">

                <div class="col-sm-5">
                    <div class="mw-full">
                        <div class="card p-0 border">
                            <img src="../../<?= $data['event']->getImage(); ?>" class="img-fluid rounded-top" alt="Event image">
                            <div class="content">
                                <h1 class="content-title font-weight-bolder text-center">
                                    <?= $data['event']->getName(); ?>
                                </h1>
                                <h6 class="content-title font-weight-light text-center">

                                </h6>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-7">
                    <div class="card p-0 border">
                        <div class="content font-weight-light">
                            <?php foreach ($data['venues'] as $venue): ?>
                                <p class="text-muted">
                                    <?= $venue->getName() . " | "; ?>
                                    <?= '<i class="fas fa-user"></i>' . " " . $venue->getCapacity(); ?>
                                </p>
                                <p class="text-muted">
                                    <?= $venue->getAddress() . ", " . $venue->getPostcode(); ?>
                                    <?= $venue->getCity(); ?>
                                </p>
                                <p class="text-muted">
                                    <?= $venue->getCountry(); ?>
                                </p>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>

                <?php foreach ($data['musicians'] as $musician): ?>
                <div  class="col-sm-12">
                    <div class="mw-full">
                        <div class="card p-0 border">
                            <img src="../../<?= $musician->getImage(); ?>" class="img-fluid rounded-top" alt="Musician image">
                            <div class="content">
                                <h3 class="content-title font-weight-bold">
                                    <?= ' | ' . $musician->getName() . ' | ' . $musician->getGenre() . ' | ' ?>
                                </h3>
                                    <?= $musician->getDescription(); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>

            </div>
        </div>
    </div>
</div>
<!-- Content wrapper end -->

    <?php include TEMPLATE_PATH . "Footer.tmpl.phtml"; ?>

</div>
<!-- Page wrapper end -->

<?php include TEMPLATE_PATH . "Scripts.tmpl.phtml"; ?>

</body>
</html>