<!DOCTYPE html>
<html lang="en">
<?php include TEMPLATE_PATH . "Head.tmpl.phtml"; ?>

<body class="dark-mode with-custom-webkit-scrollbars with-custom-css-scrollbars" data-dm-shortcut-enabled="true">

<!-- Page wrapper start -->
<div id="page-wrapper" class="page-wrapper with-navbar with-navbar-fixed-bottom">

    <!-- Register Modal -->
    <?php include VIEW_PATH . "Pages/Register.view.phtml"; ?>

    <!-- Login Modal -->
    <?php include VIEW_PATH . "Pages/Login.view.phtml"; ?>

    <!-- Sticky alerts -->
    <div class="sticky-alerts"></div>

    <?php include TEMPLATE_PATH . "Nav.tmpl.phtml"; ?>

    <!-- Content wrapper start -->
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="card border">
            <div class="row">

                <div class="col-sm-5">
                    <div class="mw-full">
                        <div class="card p-0 border">
                            <img src="<?= $data['event']->getImage(); ?>" class="img-fluid rounded-top" alt="Venue image">
                            <div class="content">
                                <h1 class="content-title font-weight-bolder text-center">
                                    <?= $data['event']->getName(); ?>
                                </h1>
                                <h6 class="content-title font-weight-light text-center">

                                </h6>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-7">
                    <div class="card p-0 border">
                        <div class="content font-weight-light">
                            <?php foreach ($data['venues'] as $venue): ?>
                                <p class="text-muted">
                                    <?= $venue->getName() . " | "; ?>
                                    <?= '<i class="fas fa-user"></i>' . " " . $venue->getCapacity(); ?>
                                </p>
                                <p class="text-muted">
                                    <?= $venue->getAddress() . ", " . $venue->getPostcode(); ?>
                                    <?= $venue->getCity(); ?>
                                </p>
                                <p class="text-muted">
                                    <?= $venue->getCountry(); ?>
                                </p>
                            <?php endforeach; ?>
                        </div>
                    </div>
                </div>

                <?php foreach ($data['musicians'] as $musician): ?>
                <div  class="col-sm-12">
                    <div class="mw-full">
                        <div class="card p-0 border">
                            <img src="<?= $musician->getImage(); ?>" class="img-fluid rounded-top" alt="Venue image">
                            <div class="content">
                                <h3 class="content-title font-weight-bold">
                                    <?= ' | ' . $musician->getName() . ' | ' . $musician->getGenre() . ' | ' ?>
                                </h3>
                                    <?= $musician->getDescription(); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>

            </div>
        </div>
    </div>
</div>
<!-- Content wrapper end -->

    <?php include TEMPLATE_PATH . "Footer.tmpl.phtml"; ?>

</div>
<!-- Page wrapper end -->

<?php include TEMPLATE_PATH . "Scripts.tmpl.phtml"; ?>

</body>
</html>