<!DOCTYPE html>
<html lang="en">
<?php include TEMPLATE_PATH . "Head.tmpl.phtml"; ?>

<body class="dark-mode with-custom-webkit-scrollbars with-custom-css-scrollbars" data-dm-shortcut-enabled="true">

<!-- Page wrapper start -->
<div id="page-wrapper" class="page-wrapper with-navbar with-navbar-fixed-bottom">

    <!-- Register Modal -->
    <?php include VIEW_PATH . "Pages/Register.view.phtml"; ?>

    <!-- Login Modal -->
    <?php include VIEW_PATH . "Pages/Login.view.phtml"; ?>

    <!-- Sticky alerts -->
    <div class="sticky-alerts"></div>

    <?php include TEMPLATE_PATH . "Nav.tmpl.phtml"; ?>

    <!-- Content wrapper start -->
    <div class="content-wrapper">

        <div class="container-fluid">

            <div class="row">
                <?php foreach ($data['events'] as $event): ?>
                    <div class="col-sm-4 col-sm-auto">
                        <div class="mw-full"> <!-- w-400 = width: 40rem (400px), mw-full = max-width: 100% -->
                            <div class="card p-0"> <!-- p-0 = padding: 0 -->
                                <img src="assets/eventzone_logo_gradient.png" class="img-fluid rounded-top" alt="Venue image">
                                <div class="content">
                                    <h2 class="content-title font-weight-bolder text-center">
                                        <?= $event->getName(); ?>
                                    </h2>
                                    <h3 class="content-title font-weight-bold">
                                        <?php foreach ($event->getEventMusicians($event->getId()) as $musician): ?>
                                            <?= " | " . $musician->getData()['name']; ?>
                                        <?php endforeach ?>
                                    </h3>
                                    <p class="text-muted">
                                        <?= $event->getStartDate() . " | " . substr($event->getStartTime(),0,-3); ?>
                                    </p>

                                    <div class="text-center pt-20"> <!-- text-right = text-align: right -->
                                        <a href="<?= URL_ROOT; ?>event/booking/<?= $event->getId(); ?>" class="btn btn-lg font-weight-bold">
                                            <i class="fas fa-money-check-alt"></i>
                                            Book event
                                        </a>
                                        <a href="<?= URL_ROOT; ?>event/view/<?= $event->getId(); ?>" class="btn btn-lg font-weight-bold">
                                            <i class="fas fa-bars"></i>
                                            Details
                                        </a>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>

        <!-- Content wrapper end -->
    </div>

    <?php include TEMPLATE_PATH . "Footer.tmpl.phtml"; ?>

</div>
<!-- Page wrapper end -->

<?php include TEMPLATE_PATH . "Scripts.tmpl.phtml"; ?>

</body>
</html>