<div class="modal" id="register" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <a href="<?= URL_ROOT; ?>" class="btn close" role="button" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </a>
            <h5 class="modal-title font-weight-bold">Register</h5>

            <form action="<?= URL_ROOT; ?>register/submit" method="POST">

                <div class="form-row row-eq-spacing-sm">
                    <!-- First name -->
                    <div class="col-sm form-group <?= isset($_SESSION['errors_arr']['name']) ? 'is-invalid' : ''; ?>">
                        <label for="first-name" class="required font-weight-bold">First name</label>
                        <input type="text" class="form-control"
                               value="<?= isset($_SESSION['data_arr']['firstName']) ? $_SESSION['data_arr']['firstName'] : ''; ?>"
                               name="first-name" id="first-name" placeholder="First name" required="required">
                        <small class="text-danger"><?= isset($_SESSION['errors']['name']) ? $_SESSION['errors']['name'] : ''; ?></small>
                    </div>

                    <!-- Last name -->
                    <div class="col-sm form-group <?= isset($_SESSION['errors_arr']['name']) ? 'is-invalid' : ''; ?>">
                        <label for="last-name" class="required font-weight-bold">Last name</label>
                        <input type="text" class="form-control"
                               value="<?= isset($_SESSION['data_arr']['lastName']) ? $_SESSION['data_arr']['lastName'] : ''; ?>"
                               name="last-name" id="last-name" placeholder="Last name" required="required">
                    </div>
                </div>

                <!-- Email -->
                <div class="form-group">
                    <label for="email" class="required font-weight-bold">Email</label>
                    <input type="email" id="email" class="form-control" name="email" placeholder="Email" required="required"
                           value="<?= isset($_SESSION['data_arr']['email']) ? $_SESSION['data_arr']['email'] : ''; ?>">
                    <small class="text-danger"><?= isset($_SESSION['errors_arr']['email']) ? $_SESSION['errors_arr']['email'] : ''; ?></small>
                </div>
                <!-- Password -->
                <div class="form-group">
                    <label for="password" class="required font-weight-bold">Password</label>
                    <input type="password" id="password" class="form-control" name="password" placeholder="Password" required="required">
                    <small class="text-danger"><?= isset($_SESSION['errors_arr']['password']) ? $_SESSION['errors_arr']['password'] : ''; ?></small>
                </div>
                <!-- Confirm password -->
                <div class="form-group">
                    <label for="confirm-password" class="required font-weight-bold">Confirm Password</label>
                    <input type="password" id="confirm-password" class="form-control" name="confirm-password" placeholder="Confirm password" required="required">
                    <small class="text-danger"><?= isset($_SESSION['errors_arr']['confirm-password']) ? $_SESSION['errors_arr']['confirm-password'] : ''; ?></small>
                    <div class="form-text">
                        Must match the above password exactly.
                    </div>
                </div>
                <input class="btn btn-primary btn-block" type="submit" value="Register">

            </form>

            <div class="text-center pt-5 mt-20">
                <a href="<?= URL_ROOT; ?>#login" class="hyperlink">Already have an account? Sign in here.</a>
            </div>

        </div>
    </div>
</div>