<!DOCTYPE html>
<html lang="en">
<?php include TEMPLATE_PATH . "Head.tmpl.phtml"; ?>
<body class="dark-mode with-custom-webkit-scrollbars with-custom-css-scrollbars" data-dm-shortcut-enabled="true" data-sidebar-shortcut-enabled="true">

<!-- Page wrapper start -->
<div id="page-wrapper" class="page-wrapper with-navbar with-sidebar" data-sidebar-type="default">

    <!-- Sticky alerts -->
    <div class="sticky-alerts"></div>

    <?php include ADMIN_TEMPLATE_PATH . "Nav.tmpl.phtml"; ?>

    <?php include ADMIN_TEMPLATE_PATH . "Sidebar.tmpl.phtml"; ?>

    <!-- Sidebar overlay -->
    <div class="sidebar-overlay" onclick="halfmoon.toggleSidebar()"></div>

    <!-- Content wrapper start -->
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row row-eq-spacing-lg">
                <div class="col-lg-12">

                    <div class="content">
                        <h3>Event List</h3>
                        <table class="table table-hover table-responsive table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Musicians</th>
                                <th>Venue</th>
                                <th>Image</th>
                                <th>Actions</th>
                            </tr>
                            </thead>

                            <tbody>

                            <?php foreach ($data['events'] as $event) :?>
                            <tr>
                                <th><?= $event->getId(); ?></th>
                                <td><?= $event->getName(); ?></td>

                                <td>
                                <?php foreach ($event->getEventMusicians($event->getId()) as $attendingMusician): ?>
                                    <div class="text-truncate w-250 pt-10 pb-10">
                                        <?= $attendingMusician->getData()['name']; ?>
                                        <a href="<?= URL_ROOT ?>musician/edit/<?= $attendingMusician->getData()['id']; ?>" class="btn btn-square btn-sm">
                                            <span>
                                                 <i class="fa fa-edit" aria-hidden="true"></i>
                                            </span>
                                        </a>
                                        <a href="<?= URL_ROOT ?>musician/view/<?= $attendingMusician->getData()['id']; ?>" class="btn btn-square btn-sm">
                                            <span>
                                                 <i class="fas fa-eye" aria-hidden="true"></i>
                                            </span>
                                        </a>
                                    </div>
                                <?php endforeach; ?>
                                </td>

                                <td>
                                <?php foreach ($event->getEventVenues($event->getId()) as $venue): ?>
                                    <div class="text-truncate w-250">
                                        <?= $venue->getData()['name']; ?>
                                        <a href="<?= URL_ROOT ?>venue/edit/<?= $venue->getData()['id']; ?>" class="btn btn-square btn-sm">
                                            <span>
                                                 <i class="fa fa-edit" aria-hidden="true"></i>
                                            </span>
                                        </a>
                                        <a href="<?= URL_ROOT ?>venue/<?= $venue->getData()['id']; ?>" class="btn btn-square btn-sm">
                                            <span>
                                                 <i class="fas fa-eye" aria-hidden="true"></i>
                                            </span>
                                        </a>
                                    </div>
                                <?php endforeach; ?>
                                </td>

                                <td><img src="<?= $event->getImage(); ?>" alt="<?= $event->getImage(); ?>"></td>
                                <td>
                                    <a href="edit/<?= $event->getId(); ?>" class="btn btn-square">
                                    <span>
                                         <i class="fa fa-edit" aria-hidden="true"></i>
                                    </span>
                                    </a>

                                    <form action="deleteSubmit/<?= $event->getId(); ?>" method="post">
                                        <button class="btn btn-square" name="deleteSubmit">
                                    <span>
                                         <i class="fa fa-trash" aria-hidden="true"></i>
                                    </span>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                            </tbody>

                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Content wrapper end -->

</div>
<!-- Page wrapper end -->
<?php include TEMPLATE_PATH . "Scripts.tmpl.phtml"; ?>

</body>
</html>
