<div class="modal" id="edit" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <a href="<?= URL_ROOT; ?>" class="btn close" role="button" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </a>
            <h5 class="modal-title font-weight-bold">Edit Administrator</h5>

            <form action="admin/editSubmit" method="post">

                <div class="form-row row-eq-spacing-sm">
                    <!-- First name -->
                    <div class="col-sm form-group <?= isset($_SESSION['errors']['name']) ? 'is-invalid' : ''; ?>">
                        <label for="first-name" class="required font-weight-bold">First name</label>
                        <input type="text" class="form-control"
                               value="<?= $admin->getFirstName(); ?>"
                               name="first-name" id="first-name" placeholder="First name" required="required">
                        <small class="text-danger"><?= isset($_SESSION['errors']['name']) ? $_SESSION['errors']['name'] : ''; ?></small>
                    </div>

                    <!-- Last name -->
                    <div class="col-sm form-group <?= isset($_SESSION['errors']['name']) ? 'is-invalid' : ''; ?>">
                        <label for="last-name" class="required font-weight-bold">Last name</label>
                        <input type="text" class="form-control"
                               value="<?= $admin->getLastName(); ?>"
                               name="last-name" id="last-name" placeholder="Last name" required="required">
                    </div>
                </div>

                <!-- Email -->
                <div class="form-group">
                    <label for="email" class="required font-weight-bold">Email</label>
                    <input type="email" id="email" class="form-control" name="email" placeholder="Email" required="required"
                           value="<?= $admin->getEmail(); ?>"
                    <small class="text-danger"><?= isset($_SESSION['errors']['email']) ? $_SESSION['errors']['email'] : ''; ?></small>
                </div>
                <input class="btn btn-primary btn-block" type="submit" value="Update">

            </form>

        </div>
    </div>
</div>